//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoturBeniIstedigimYere.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheckinDatasetEntities4 : DbContext
    {
        public CheckinDatasetEntities4()
            : base("name=CheckinDatasetEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<CategoryProfile> CategoryProfile { get; set; }
        public virtual DbSet<Checkin> Checkin { get; set; }
        public virtual DbSet<LikeCategories> LikeCategories { get; set; }
        public virtual DbSet<Likes> Likes { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<PlaceCategories> PlaceCategories { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Token> Token { get; set; }
        public virtual DbSet<TRIPADVISORPLACES> TRIPADVISORPLACES { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserLikes> UserLikes { get; set; }
        public virtual DbSet<UserLoginInfo> UserLoginInfo { get; set; }
    }
}
