//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoturBeniIstedigimYere.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkin
    {
        public int CHECKINID { get; set; }
        public Nullable<int> PLACEID { get; set; }
        public Nullable<int> POSTID { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<int> LIKECOUNT { get; set; }
        public Nullable<int> WITHCOUT { get; set; }
        public Nullable<int> SCORE { get; set; }
        public string SHOUT { get; set; }
    }
}
