//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoturBeniIstedigimYere.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int PLACEID { get; set; }
        public string SWARMID { get; set; }
        public string NAME { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string ADDRESS { get; set; }
        public string LAT { get; set; }
        public string LNG { get; set; }
        public Nullable<int> CHECKINSCOUNT { get; set; }
        public Nullable<int> TIPCOUNT { get; set; }
        public Nullable<int> USERSCOUNT { get; set; }
    }
}
