//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoturBeniIstedigimYere.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceCategories
    {
        public int PLACECATEGORIEID { get; set; }
        public Nullable<int> PLACEID { get; set; }
        public Nullable<int> CATEGORIEID { get; set; }
    }
}
