//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoturBeniIstedigimYere.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> FAVORITESCOUNT { get; set; }
        public Nullable<int> FOLLOWERSCOUNT { get; set; }
        public Nullable<int> FRIENDSCOUNT { get; set; }
        public string LOCATION { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string SEX { get; set; }
        public string URL { get; set; }
        public string TWID { get; set; }
        public string SWID { get; set; }
    }
}
