//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web2.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryProfile
    {
        public int CATEGORYPROFILEID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string FEATURES { get; set; }
    }
}
