//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web2.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int POSTID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string TWEETID { get; set; }
        public string TEXT { get; set; }
        public string SOURCE { get; set; }
        public string SHORTLINK { get; set; }
        public string SWARMCHECKINID { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
    }
}
