//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web2.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLikes
    {
        public int USERLIKEID { get; set; }
        public Nullable<int> USERLOGINID { get; set; }
        public Nullable<int> LIKEID { get; set; }
        public Nullable<int> VALUE { get; set; }
    }
}
